### ISSUE TITLE
Adeptus Arbites Cyber-Mastiffs Issue

### ISSUE THREAD

**Issue by Lord-Falkenrath** [Mad-Spy/40kHomeBrew#1]
In the 9e version of the Arbites .cat file, the Cyber Mastiff entry in the elites section does not provide a statline for movement, WS/BS, Str/Toughness, Save value, etc. However, when adding the cyber-mastiff option to marshals and judges, the proper statline as presented in the pdf codex is present on those entries. I have attached screenshots to illustrate my point, though I am not a coder and can't say why this is happening.
![Screenshot (1)](https://user-images.githubusercontent.com/70852237/92329191-ceb22080-f033-11ea-9003-0d3185574320.png)
![Screenshot (2)](https://user-images.githubusercontent.com/70852237/92329193-cfe34d80-f033-11ea-8785-8b7c80ded6c0.png)

**Comment by Mad-Spy** [comment]
Fixed in v6 of the 8th ed file and v7 of the 9th ed file.
