### ISSUE TITLE
Faith Militant Loading Issues

### ISSUE THREAD

**Issue by Runnerbrax** [Mad-Spy/40kHomeBrew#5]
When attempting to load Imperium - Faith Militant v3 on Android OS (any detachment) the following message appears: "You do not have the data files needed to edit this roster. The roster will be displayed for viewing instead"

Have attempted to recreate the error on Fallen Sororitas and Adeptus Arbites. So far it only happens on Faith Militant.

When attempting to load Imperium - Faith Militant v3 on Battlescribe application on Microsoft Windows, two errors occur.

1. When creating any detachment, if Faith Militant is the first detachment I try to load, the selecting the "OK" button at the bottom of the "New Roster" window doesn't load to the main screen.

2. When creating any detachment, after that detachment has been properly loaded, if I select the "Change Roster Details" icon on the menu bar and attempt to load any Faith Militant detachment I get the following error message:

Details:
There was an error finding one or more data files.
1) Imperium - Inquisition:aa2c-e8f4-0303-bede:net.battlescribe.model.data.CatalogueLink@19eb18b: No catalogue found with ID e373-3c0a-1185-46ea
at net.battlescribe.engine.b.f.a(BattleScribe:602)

**Comment by Mad-Spy** [comment]
The Inquisition file guid in the 8th ed data got changed and the Faith Militant file never got updated. Now fixed.
